In [1]:
#Instalación de librerías
!pip install pandas numpy matplotlib seaborn plotly
!pip install nbformat>=4.2.0

Requirement already satisfied: pandas in c:\users\dave\.conda\envs\tf310\lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\users\dave\.conda\envs\tf310\lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in c:\users\dave\.conda\envs\tf310\lib\site-packages (3.7.5)
Requirement already satisfied: seaborn in c:\users\dave\.conda\envs\tf310\lib\site-packages (0.13.2)
Requirement already satisfied: plotly in c:\users\dave\.conda\envs\tf310\lib\site-packages (6.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from matplotlib) (4.58.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from matplotlib) (11.2.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from plotly) (1.38.2)
Requirement already satisfied: six>=1.5 in c:\users\dave\.conda\envs\tf310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
#Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Análisis Exploratorio de los Datos

In [6]:
# Ruta de los datos
path = 'data/Raw/'

## Catálogo de Productos

In [7]:
catalogo = pd.read_csv(path + 'catalogo_productos.csv')
# Se imprimen las primeras 10 filas del DataFrame para verificar que se haya cargado correctamente
catalogo.head(10)

,id_producto,nombre,categoria,costo_unitario,precio_venta,costo_almacenamiento_semanal
0,PROD_001,Tinto,Bebidas,800,2500,10
1,PROD_002,Café con Leche,Bebidas,1200,3500,15
2,PROD_003,Cappuccino,Bebidas,1500,4500,15
3,PROD_004,Pan de Bono,Alimentos,1000,2800,20
4,PROD_005,Buñuelo,Alimentos,800,2500,20
5,PROD_006,Croissant,Alimentos,1200,3500,25
6,PROD_007,Pastel de Pollo,Alimentos,1500,3500,30
7,PROD_008,Jugo de Naranja,Bebidas,2000,5000,50

In [5]:
#Se valida la estructura del DataFrame y los vacíos de las columnas
catalogo.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   id_producto                   8 non-null      str
 1   nombre                        8 non-null      str
 2   categoria                     8 non-null      str
 3   costo_unitario                8 non-null      int64
 4   precio_venta                  8 non-null      int64
 5   costo_almacenamiento_semanal  8 non-null      int64
dtypes: int64(3), str(3)
memory usage: 516.0 bytes

In [4]:
# Se obtiene el número de productos y categorías únicas en el catálogo
n_productos = catalogo.id_producto.nunique()
n_categorias = catalogo.categoria.nunique()
print(f"El catálogo contiene {n_productos} productos únicos y {n_categorias} categorías únicas.")
print(f"Los productos son: {catalogo.nombre.unique().tolist()}")
print(f"Las categorías son: {catalogo.categoria.unique().tolist()}")

El catálogo contiene 8 productos únicos y 2 categorías únicas.
Los productos son: ['Tinto', 'Café con Leche', 'Cappuccino', 'Pan de Bono', 'Buñuelo', 'Croissant', 'Pastel de Pollo', 'Jugo de Naranja']
Las categorías son: ['Bebidas', 'Alimentos']

In [6]:
#Se validan los máximos y mínimos de las columnas de tipo numérico y se identifican los productos que corresponden a esos valores
#Máximos
costo_maximo = catalogo.costo_unitario.max()
productos_costo = ", ".join(catalogo.loc[catalogo.costo_unitario == costo_maximo, "nombre"])
precio_venta_maximo = catalogo.precio_venta.max()
productos_precio = ", ".join(catalogo.loc[catalogo.precio_venta == precio_venta_maximo, "nombre"])
costo_alamcenamiento = catalogo.costo_almacenamiento_semanal.max()
productos_almacenamiento = ", ".join(catalogo.loc[catalogo.costo_almacenamiento_semanal == costo_alamcenamiento, "nombre"])

#Mínimos
costo_minimo = catalogo.costo_unitario.min()
productos_costo_minimo = ", ".join(catalogo.loc[catalogo.costo_unitario == costo_minimo, "nombre"])
precio_venta_minimo = catalogo.precio_venta.min()
productos_precio_minimo = ", ".join(catalogo.loc[catalogo.precio_venta == precio_venta_minimo, "nombre"])
costo_almacenamiento_minimo = catalogo.costo_almacenamiento_semanal.min()
productos_almacenamiento_minimo = ", ".join(catalogo.loc[catalogo.costo_almacenamiento_semanal == costo_almacenamiento_minimo, "nombre"])

print('MÁXIMOS:')
print(f"El costo unitario máximo es: {costo_maximo}, que corresponde a: {productos_costo}")
print(f"El precio de venta máximo es: {precio_venta_maximo}, que corresponde a: {productos_precio}")
print(f"El costo de almacenamiento máximo es: {costo_alamcenamiento}, que corresponde a: {productos_almacenamiento}")
print('MÍNIMOS:')
print(f"El costo unitario mínimo es: {costo_minimo}, que corresponde a: {productos_costo_minimo}")
print(f"El precio de venta mínimo es: {precio_venta_minimo}, que corresponde a: {productos_precio_minimo}")
print(f"El costo de almacenamiento mínimo es: {costo_almacenamiento_minimo}, que corresponde a: {productos_almacenamiento_minimo}")

MÁXIMOS:
El costo unitario máximo es: 2000, que corresponde a: Jugo de Naranja
El precio de venta máximo es: 5000, que corresponde a: Jugo de Naranja
El costo de almacenamiento máximo es: 50, que corresponde a: Jugo de Naranja
MÍNIMOS:
El costo unitario mínimo es: 800, que corresponde a: Tinto, Buñuelo
El precio de venta mínimo es: 2500, que corresponde a: Tinto, Buñuelo
El costo de almacenamiento mínimo es: 10, que corresponde a: Tinto

## Maestro Tiendas

In [ ]:
tiendas = pd.read_csv(path + 'maestro_tiendas.csv')
# Se imprimen las primeras 10 filas del DataFrame para verificar que se haya cargado correctamente
tiendas.head(10)

  id_tienda    ciudad  tamaño_m2
0  STORE_01    Bogotá         28
1  STORE_02    Bogotá         43
2  STORE_03    Bogotá         42
3  STORE_04      Cali         40
4  STORE_05    Bogotá         34
5  STORE_06    Bogotá         34
6  STORE_07    Bogotá         15
7  STORE_08    Bogotá         49
8  STORE_09  Medellín         25
9  STORE_10    Bogotá         32

In [9]:
#Se valida la estructura del DataFrame y los vacíos de las columnas
tiendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_tienda  20 non-null     str
 1   ciudad     20 non-null     str
 2   tamaño_m2  20 non-null     int64
dtypes: int64(1), str(2)
memory usage: 612.0 bytes

In [10]:
# Se obtiene el número de tiendas y ciudades únicas en la tabla de tiendas
n_tiendas = tiendas.id_tienda.nunique()
n_ciudades = tiendas.ciudad.nunique()
print(f"Hay {n_tiendas} tiendas repartidas en {n_ciudades} ciudades.")
print(f"Los tiendas son: {tiendas.id_tienda.unique().tolist()}")
print(f"Las ciudades son: {tiendas.ciudad.unique().tolist()}")

# Se obtiene el número de tiendas por ciudad
num_tiendas_ciudad =tiendas.groupby('ciudad').agg(
    total_tiendas=('id_tienda', 'nunique')
).reset_index().sort_values(by='total_tiendas', ascending=False)

num_tiendas_ciudad

Hay 20 tiendas repartidas en 3 ciudades.
Los tiendas son: ['STORE_01', 'STORE_02', 'STORE_03', 'STORE_04', 'STORE_05', 'STORE_06', 'STORE_07', 'STORE_08', 'STORE_09', 'STORE_10', 'STORE_11', 'STORE_12', 'STORE_13', 'STORE_14', 'STORE_15', 'STORE_16', 'STORE_17', 'STORE_18', 'STORE_19', 'STORE_20']
Las ciudades son: ['Bogotá', 'Cali', 'Medellín']

     ciudad  total_tiendas
0    Bogotá             14
2  Medellín              5
1      Cali              1

In [11]:
# Se revisa la distribución del tamaño en m2 de las tiendas
print(tiendas.describe())
print("\n")

# Se revisa la distribución del tamaño en m2 de las tiendas por ciudad
for ciudad in tiendas.ciudad.unique():
    print(f"Distribución del tamaño de las tiendas en {ciudad}:")
    print(tiendas[tiendas.ciudad == ciudad]['tamaño_m2'].describe())
    print("\n")

       tamaño_m2
count  20.000000
mean   34.200000
std     8.507582
min    15.000000
25%    31.750000
50%    34.000000
75%    38.500000
max    49.000000


Distribución del tamaño de las tiendas en Bogotá:
count    14.000000
mean     35.785714
std       8.675151
min      15.000000
25%      33.000000
50%      34.000000
75%      41.000000
max      49.000000
Name: tamaño_m2, dtype: float64


Distribución del tamaño de las tiendas en Cali:
count     1.0
mean     40.0
std       NaN
min      40.0
25%      40.0
50%      40.0
75%      40.0
max      40.0
Name: tamaño_m2, dtype: float64


Distribución del tamaño de las tiendas en Medellín:
count     5.000000
mean     28.600000
std       6.542171
min      19.000000
25%      25.000000
50%      31.000000
75%      33.000000
max      35.000000
Name: tamaño_m2, dtype: float64

- Las tiendas están entre los 15m2 y los 49m2 con un tamaño promedio de 34.2m2.
- En Bogotá las tiendas son un poco más grandes, con un tamaño promedio de 35.8m2 vs 28.6m2 de Medellín. En Cali la única tienda que hay tiene un tamaño de 40m2

## Inventario Actual

In [ ]:
inventario = pd.read_csv(path + 'inventario_actual.csv')
# Se imprimen las primeras 10 filas del DataFrame para verificar que se haya cargado correctamente
inventario.head(10)

  id_tienda id_producto  stock_actual
0  STORE_01    PROD_001             1
1  STORE_01    PROD_002            10
2  STORE_01    PROD_003            33
3  STORE_01    PROD_004            11
4  STORE_01    PROD_005             3
5  STORE_01    PROD_006            13
6  STORE_01    PROD_007             8
7  STORE_01    PROD_008            13
8  STORE_02    PROD_001             9
9  STORE_02    PROD_002            20

In [13]:
#Se valida la estructura del DataFrame y los vacíos de las columnas
inventario.info()

<class 'pandas.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_tienda     160 non-null    str
 1   id_producto   160 non-null    str
 2   stock_actual  160 non-null    int64
dtypes: int64(1), str(2)
memory usage: 3.9 KB

In [14]:
# Se obtiene el número de tiendas
n_tiendas = inventario.id_tienda.nunique()
print(f"El catálogo contiene {n_tiendas} tiendas únicas.")

El catálogo contiene 20 tiendas únicas.

In [16]:
#Se van a validar cual es el prodcuto con mayor y menor cantidad de inventario por tienda,
#para esto se va a hacer un merge entre el inventario y el catálogo para obtener el nombre del producto

inventario_nombres = inventario.merge(catalogo[['id_producto', 'nombre']], on='id_producto', how='left')
tiendas_stock_stats = (
    inventario_nombres.groupby('id_tienda')
    .agg(
        producto_mayor_stock=('nombre', lambda x: x[inventario_nombres.loc[x.index, 'stock_actual'].idxmax()]),
        mayor_stock=('stock_actual', 'max'),
        producto_menor_stock=('nombre', lambda x: x[inventario_nombres.loc[x.index, 'stock_actual'].idxmin()]),
        menor_stock=('stock_actual', 'min')
    )
    .reset_index()
)

tiendas_stock_stats

,id_tienda,producto_mayor_stock,mayor_stock,producto_menor_stock,menor_stock
0,STORE_01,Cappuccino,33,Tinto,1
1,STORE_02,Pan de Bono,43,Croissant,8
2,STORE_03,Café con Leche,24,Tinto,4
3,STORE_04,Jugo de Naranja,36,Buñuelo,5
4,STORE_05,Tinto,38,Buñuelo,1
5,STORE_06,Cappuccino,43,Tinto,3
6,STORE_07,Pan de Bono,55,Buñuelo,0
7,STORE_08,Pan de Bono,62,Cappuccino,0
8,STORE_09,Tinto,75,Cappuccino,2
9,STORE_10,Cappuccino,57,Pan de Bono,1
10,STORE_11,Croissant,89,Café con Leche,0
11,STORE_12,Jugo de Naranja,97,Pastel de Pollo,1
12,STORE_13,Croissant,49,Pastel de Pollo,2
13,STORE_14,Buñuelo,41,Tinto,4
14,STORE_15,Buñuelo,51,Pastel de Pollo,8
15,STORE_16,Cappuccino,47,Croissant,3
16,STORE_17,Café con Leche,37,Tinto,0
17,STORE_18,Jugo de Naranja,36,Pan de Bono,3
18,STORE_19,Pan de Bono,25,Pastel de Pollo,0
19,STORE_20,Pastel de Pollo,54,Café con Leche,3

Hay varias tiendas que en el momento no tienen stock de alguno de los productos:
- STORE_07: Buñuelo
- STORE_08: Capuccino
- STORE_11: Café con Leche
- STORE_17: Tinto
- STORE_19: Pastel de Pollo

In [17]:
#Se revisa el inventario total por producto
inventario_productos = (
    inventario_nombres.groupby('nombre')
    .agg(
        stock_total=('stock_actual', 'sum')
    )
)

print(f'El inventario promedio por producto es: {round(inventario_productos["stock_total"].mean(), 1)}')

inventario_productos.sort_values(by='stock_total', ascending=False).head(10)

El inventario promedio por producto es: 420.9

                 stock_total
nombre
Pan de Bono              486
Jugo de Naranja          462
Croissant                453
Cappuccino               435
Tinto                    434
Buñuelo                  393
Pastel de Pollo          353
Café con Leche           351

*El producto con mayor stock entre las tiendas es el Pan de Bono y el de menos es el Café con Leche*

In [18]:
#Se revisan los inventarios por ciudad, para esto se hace un merge entre el inventario y las tiendas para obtener la ciudad de cada tienda
inventario_ciudad = inventario_nombres.merge(tiendas[['id_tienda', 'ciudad']], on='id_tienda', how='left')

inventario_ciudad_stats = (
    inventario_ciudad.groupby(['ciudad', 'nombre'])
    .agg(
        stock_total=('stock_actual', 'sum'),
        stock_promedio=('stock_actual', 'mean'),
        stock_maximo=('stock_actual', 'max'),
        stock_minimo=('stock_actual', 'min')
    )
)

inventario_ciudad_stats.sort_values(by='stock_total', ascending=False)

                          stock_total  stock_promedio  stock_maximo  \
ciudad   nombre
Bogotá   Cappuccino               374       26.714286            57
         Croissant                341       24.357143            89
         Pan de Bono              330       23.571429            62
         Buñuelo                  289       20.642857            52
         Tinto                    254       18.142857            45
         Jugo de Naranja          254       18.142857            38
         Café con Leche           240       17.142857            37
         Pastel de Pollo          208       14.857143            56
Medellín Jugo de Naranja          172       34.400000            97
         Tinto                    151       30.200000            75
         Pan de Bono              150       30.000000            42
         Pastel de Pollo          114       22.800000            54
         Café con Leche           102       20.400000            44
         Buñuelo                   99       19.800000            29
         Croissant                 82       16.400000            49
         Cappuccino                46        9.200000            19
Cali     Jugo de Naranja           36       36.000000            36
         Pastel de Pollo           31       31.000000            31
         Croissant                 30       30.000000            30
         Tinto                     29       29.000000            29
         Cappuccino                15       15.000000            15
         Café con Leche             9        9.000000             9
         Pan de Bono                6        6.000000             6
         Buñuelo                    5        5.000000             5

                          stock_minimo
ciudad   nombre
Bogotá   Cappuccino                  0
         Croissant                   3
         Pan de Bono                 1
         Buñuelo                     0
         Tinto                       1
         Jugo de Naranja             3
         Café con Leche              0
         Pastel de Pollo             0
Medellín Jugo de Naranja             7
         Tinto                       0
         Pan de Bono                11
         Pastel de Pollo             1
         Café con Leche              3
         Buñuelo                     2
         Croissant                   2
         Cappuccino                  2
Cali     Jugo de Naranja            36
         Pastel de Pollo            31
         Croissant                  30
         Tinto                      29
         Cappuccino                 15
         Café con Leche              9
         Pan de Bono                 6
         Buñuelo                     5

- En Bogota el producto con mayor stock es el Cappuccino, y el pastel de pollo es el de menor stock
- En Medellín y Cali el Jugo de Naranaja presenta el mayor stock mientras que el Capucciono tiene el menor stock para Medellín y el Buñuelo en Cali

## Ventas Históricas

In [ ]:
ventas = pd.read_csv(path + 'ventas_historicas.csv')
# Se imprimen las primeras 10 filas del DataFrame para verificar que se haya cargado correctamente
ventas.head(10)

        fecha id_tienda id_producto  unidades_vendidas
0  2024-01-01  STORE_01    PROD_001                  5
1  2024-01-02  STORE_01    PROD_001                  4
2  2024-01-03  STORE_01    PROD_001                  3
3  2024-01-04  STORE_01    PROD_001                  4
4  2024-01-05  STORE_01    PROD_001                 10
5  2024-01-06  STORE_01    PROD_001                  8
6  2024-01-07  STORE_01    PROD_001                  8
7  2024-01-08  STORE_01    PROD_001                  8
8  2024-01-09  STORE_01    PROD_001                  4
9  2024-01-10  STORE_01    PROD_001                  3

In [20]:
#Se valida la estructura del DataFrame y los vacíos de las columnas
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 14560 entries, 0 to 14559
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha              14560 non-null  str
 1   id_tienda          14560 non-null  str
 2   id_producto        14560 non-null  str
 3   unidades_vendidas  14560 non-null  int64
dtypes: int64(1), str(3)
memory usage: 455.1 KB

In [21]:
# Se convierte el campo fecha a tipo datetime
ventas['fecha'] = pd.to_datetime(ventas['fecha'])

min_fecha = ventas['fecha'].min()
max_fecha = ventas['fecha'].max()
num_dias = ventas['fecha'].nunique()
num_semanas = ventas['fecha'].dt.to_period('W').nunique()


print(f"""se tienen ventas para el periodo comprendido entre {min_fecha.date()} y {max_fecha.date()}.
Esto equivale a un total de {num_dias} días y {num_semanas} semanas
""")

se tienen ventas para el periodo comprendido entre 2024-01-01 y 2024-03-31.
Esto equivale a un total de 91 días y 13 semanas

In [22]:
# Se van a revisar las ventas por ciudad, para esto se hace un merge entre las ventas y las tiendas para obtener la ciudad de cada tienda
# Además se hace un merge con el catálogo para obtener el nombre del producto vendido

ventas_ciudad = ventas.merge(tiendas[['id_tienda', 'ciudad']], on='id_tienda', how='left')\
    .merge(catalogo[['id_producto', 'nombre']], on='id_producto', how='left')

ventas_ciudad_stats = (
    ventas_ciudad.groupby(['ciudad', 'nombre'])
    .agg(
        ventas_totales=('unidades_vendidas', 'sum'),
        ventas_promedio=('unidades_vendidas', 'mean'),
        ventas_maximas=('unidades_vendidas', 'max'),
        ventas_minimas=('unidades_vendidas', 'min')
    )
)

ventas_ciudad_stats.sort_values(by='ventas_totales', ascending=False)

                          ventas_totales  ventas_promedio  ventas_maximas  \
ciudad   nombre
Bogotá   Buñuelo                   24050        18.877551              56
         Pastel de Pollo           23478        18.428571              58
         Croissant                 21173        16.619309              47
         Jugo de Naranja           20859        16.372841              56
         Café con Leche            15391        12.080848              40
         Cappuccino                15248        11.968603              34
         Tinto                     10815         8.489011              31
         Pan de Bono                9066         7.116170              21
Medellín Jugo de Naranja            6795        14.934066              40
         Buñuelo                    6715        14.758242              39
         Pastel de Pollo            6534        14.360440              43
         Croissant                  5686        12.496703              34
         Cappuccino                 4799        10.547253              28
         Café con Leche             4093         8.995604              27
         Tinto                      3257         7.158242              20
         Pan de Bono                2621         5.760440              19
Cali     Jugo de Naranja            2179        23.945055              44
         Croissant                  2036        22.373626              41
         Buñuelo                    1724        18.945055              42
         Pastel de Pollo            1457        16.010989              28
         Cappuccino                 1202        13.208791              24
         Café con Leche             1096        12.043956              31
         Tinto                       899         9.879121              23
         Pan de Bono                 688         7.560440              20

                          ventas_minimas
ciudad   nombre
Bogotá   Buñuelo                       0
         Pastel de Pollo               1
         Croissant                     2
         Jugo de Naranja               1
         Café con Leche                1
         Cappuccino                    0
         Tinto                         0
         Pan de Bono                   0
Medellín Jugo de Naranja               1
         Buñuelo                       0
         Pastel de Pollo               1
         Croissant                     1
         Cappuccino                    1
         Café con Leche                1
         Tinto                         0
         Pan de Bono                   0
Cali     Jugo de Naranja               8
         Croissant                    10
         Buñuelo                       3
         Pastel de Pollo               6
         Cappuccino                    2
         Café con Leche                3
         Tinto                         2
         Pan de Bono                   0

In [23]:
#Se cuentan cuantas ventas (días de venta) se tienen por producto y ciudad
ventas_diarias = (
    ventas_ciudad.groupby(['ciudad', 'nombre'])
    .agg(
        dias_venta=('fecha', 'nunique')
    )
)

ventas_diarias

                          dias_venta
ciudad   nombre
Bogotá   Buñuelo                  91
         Café con Leche           91
         Cappuccino               91
         Croissant                91
         Jugo de Naranja          91
         Pan de Bono              91
         Pastel de Pollo          91
         Tinto                    91
Cali     Buñuelo                  91
         Café con Leche           91
         Cappuccino               91
         Croissant                91
         Jugo de Naranja          91
         Pan de Bono              91
         Pastel de Pollo          91
         Tinto                    91
Medellín Buñuelo                  91
         Café con Leche           91
         Cappuccino               91
         Croissant                91
         Jugo de Naranja          91
         Pan de Bono              91
         Pastel de Pollo          91
         Tinto                    91

*Los ocho productos tienen ventas todos los días del periodo análizado*

# Análisis ventas por semana

In [27]:
# Se unen las fuentes de datos para obtener un DataFrame con la información completa
data = ventas.merge(catalogo, on='id_producto', how='left').merge(tiendas, on='id_tienda', how='left').merge(inventario, on=['id_tienda', 'id_producto'], how='left')

# Se convierte la columna 'fecha' a tipo datetime para facilitar el análisis temporal
data['fecha'] = pd.to_datetime(data['fecha'])

# Se crea la columna de semana año para agrupar las ventas por semana
data['semana'] = data['fecha'].dt.isocalendar().week

# Se imprimen las primeras 10 filas del DataFrame para verificar que se haya cargado correctamente
data.head(10)

,fecha,id_tienda,id_producto,unidades_vendidas,nombre,categoria,costo_unitario,precio_venta,costo_almacenamiento_semanal,ciudad,tamaño_m2,stock_actual,semana
0,2024-01-01,STORE_01,PROD_001,5,Tinto,Bebidas,800,2500,10,Bogotá,28,1,1
1,2024-01-02,STORE_01,PROD_001,4,Tinto,Bebidas,800,2500,10,Bogotá,28,1,1
2,2024-01-03,STORE_01,PROD_001,3,Tinto,Bebidas,800,2500,10,Bogotá,28,1,1
3,2024-01-04,STORE_01,PROD_001,4,Tinto,Bebidas,800,2500,10,Bogotá,28,1,1
4,2024-01-05,STORE_01,PROD_001,10,Tinto,Bebidas,800,2500,10,Bogotá,28,1,1
5,2024-01-06,STORE_01,PROD_001,8,Tinto,Bebidas,800,2500,10,Bogotá,28,1,1
6,2024-01-07,STORE_01,PROD_001,8,Tinto,Bebidas,800,2500,10,Bogotá,28,1,1
7,2024-01-08,STORE_01,PROD_001,8,Tinto,Bebidas,800,2500,10,Bogotá,28,1,2
8,2024-01-09,STORE_01,PROD_001,4,Tinto,Bebidas,800,2500,10,Bogotá,28,1,2
9,2024-01-10,STORE_01,PROD_001,3,Tinto,Bebidas,800,2500,10,Bogotá,28,1,2

In [37]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Se revisa la evolución en el tiempo de las ventas por producto y ciudad
ventas_semana = (
    data.groupby(['semana', 'ciudad', 'nombre'])
    .agg(
        ventas_semanales=('unidades_vendidas', 'sum')
    )
    .reset_index()
)


ciudades = sorted(ventas_semana['ciudad'].unique())
productos = sorted(ventas_semana['nombre'].unique())

# Se realiza un gráfico que muestra las ventas semanales en el tiempo y las compara con posibles outlier, usando el rango intercuartil
fig = make_subplots(
    rows=len(ciudades),
    cols=1,
    subplot_titles=ciudades,
    shared_xaxes=True
)

# Diccionario para rastrear la relación de cada traza con su producto
trace_product_map = []
primer_producto = productos[0]

# Se agregan los trazos de las ventas y los límiter superiro e inferior
for producto in productos:
    es_primer_prod = (producto == primer_producto)

    for c_idx, ciudad in enumerate(ciudades, start=1):
        df = ventas_semana[
            (ventas_semana['ciudad'] == ciudad) &
            (ventas_semana['nombre'] == producto)
        ].sort_values('semana')
        
        # Cálculo de Outliers (IQR)
        q1 = df['ventas_semanales'].quantile(0.25)
        q3 = df['ventas_semanales'].quantile(0.75)
        ric = q3 - q1
        limite_inferior = max(0, q1 - 1.5 * ric)
        limite_superior = q3 + 1.5 * ric

        # Ventas Semanales
        fig.add_trace(
            go.Scatter(
                x=df['semana'],
                y=df['ventas_semanales'],
                mode='lines+markers',
                name=producto,
                legendgroup=producto,
                showlegend=(c_idx == 1),
                visible=es_primer_prod
            ),
            row=c_idx, col=1
        )
        trace_product_map.append(producto)

        # Límite Superior
        fig.add_trace(
            go.Scatter(
                x=df['semana'],
                y=[limite_superior] * len(df),
                mode='lines',
                line=dict(dash='dash', width=1.5, color='red'),
                name=f'Lím. Sup. ({producto})',
                legendgroup=producto,
                showlegend=False,
                hoverinfo='text',
                hovertext=f'Lím. Superior {producto}: {limite_superior:.1f}',
                visible=es_primer_prod
            ),
            row=c_idx, col=1
        )
        trace_product_map.append(producto)

        # Límite Inferior
        fig.add_trace(
            go.Scatter(
                x=df['semana'],
                y=[limite_inferior] * len(df),
                mode='lines',
                line=dict(dash='dash', width=1.5, color='orange'),
                name=f'Lím. Inf. ({producto})',
                legendgroup=producto,
                showlegend=False,
                hoverinfo='text',
                hovertext=f'Lím. Inferior {producto}: {limite_inferior:.1f}',
                visible=es_primer_prod
            ),
            row=c_idx, col=1
        )
        trace_product_map.append(producto)

# Se configuran los botones del menú desplegable
buttons = []
for producto in productos:
    visible = [p == producto for p in trace_product_map]
    buttons.append(
        dict(
            label=producto,
            method='update',
            args=[{'visible': visible}, {'title': f'Ventas semanales y outliers - {producto}'}]
        )
    )

# Se ajusta el layout final
fig.update_layout(
    title=f'Ventas Semanales y Outliers - {primer_producto}',
    updatemenus=[dict(buttons=buttons, direction='down', x=0.0, y=1.05, showactive=True)],
    height=320 * len(ciudades),
    width=950,
    legend_title='Producto'
)

fig.update_xaxes(title_text='Semana')
fig.update_yaxes(title_text='Ventas semanales')

fig

Análisando las gráficas para cada uno de los 8 productos se encuentra que:
1. Buñuelos: 
- En la **semana 2**, para **Bogotá** se tomaron valores por debajo del límite inferior (posible outlier de un valor muy bajo para la ciudad)
- En la **semana 9**, para **Cali** se tomaron valores por encima del límite superior (posible outlier de un valor muy alto para la ciudad)
2. Café con Leche:
- En la **semana 11**, para **Bogotá** se tomaron valores por encima del límite superior (posible outlier de un valor muy alto para la ciudad)
3. Capuccino:
- En las **semanas 5 y 12**, para **Bogotá** se tomaron valores por debajo del límite inferior (posibles outliers de un valor muy bajo para la ciudad)
4. Croissant: No se evindencian posibles outliers  

5. Jugo de Naranja: No se evindencian posibles outliers  
6. Pan de Bono: No se evindencian posibles outliers  
7. Pasel de Pollo:
- En la **semana 13**, para **Bogotá** se tomaron valores cercanos del límite superior (posible outlier de un valor muy alto para la ciudad)
8. Tinto: No se evindencian posibles outliers. Sin embargo, en **Medellín** en la semana 3 se observan valores cercanos al límite superior, siendo un comportamiento fuera del normal.

**Preguntas para negocio:**
- ¿Hubo algun descuento o campaña relacionada con los picos de ventas que podrían considerarse como outliers?
- ¿Para aquellas semanas con una caída en las ventas significativa (valores por debajo del límite inferior) se debió a algun tema de desabastecimiento?